In [6]:
# import pandas as pd
import pandas as pd
df = pd.read_csv("./training_dataset/data.csv")
data=pd.DataFrame({
"red": df.iloc[:, 0],
"green": df.iloc[:, 1],
"blue": df.iloc[:, 2],
"label": df.iloc[:, -1]
})
data.head(12)

    red  green  blue   label
0    20    139   240    Blue
1   174     83    72   Brown
2   144    249   131   Green
3   168     25   156    Pink
4    30    182   136   Green
5   199    150   175    Pink
6   199     93   154    Pink
7   231    243    25  Yellow
8    48    213    76   Green
9    38      3    64    Blue
10   82    181    56   Green
11  249     99   108    Pink